#!/bin/bash -eu

sudo apt-get -y update dist-upgrade autoremove

unset pkgs
pkgs+=asciidoc
pkgs+=docbook2x
pkgs+=gcc
pkgs+=gettext
pkgs+=git 
pkgs+=libcurl4-openssl-dev
pkgs+=libexpat1-dev
pkgs+=libssl-dev
pkgs+=make
pkgs+=openssl
sudo apt-get -y $pkgs

ssh-keygen
# now copy the public key to GitHub

git clone git@github.com:jsh/home
for i in home/.b* home/.v*; do
  ln $i $HOME
done

git clone git@github.com:git/git.git
cd git
make prefix=/usr all doc info
sudo make prefix=/usr install install-doc install-html install-info 
