#!/bin/bash -eu

sudo apt-get -y update dist-upgrade autoremove

unset pkgs
pkgs+=asciidoc
pkgs+=docbook2x
pkgs+=gcc
pkgs+=gettext
pkgs+=git 
pkgs+=libcurl4-openssl-dev
pkgs+=libexpat1-dev
pkgs+=libssl-dev
pkgs+=make
pkgs+=openssl
pkgs+=tree
sudo apt-get -y $pkgs
git config --global user.name "Jeffrey S. Haemer"
git config --global user.email "jeffrey.haemer@gmail.com"

ssh-keygen
# now copy the public key to GitHub

for i in jsh/{git-scratch,home} git/git; do
  [ -d $(basename $i) ] || git clone $i
done

for i in home/.b* home/.v*; do
  ln -f $i $HOME
done

make -C git prefix=/usr all doc info
sudo make -C git prefix=/usr install install-doc install-html install-info 

mkdir -p ~/bin
ln -f git-scratch/git-{addfile,scratch} $_

