#!/bin/bash -eu

cd
sudo apt-get -y update > /dev/null
sudo apt-get -y dist-upgrade
sudo apt-get -y autoremove

unset pkgs
pkgs+=' asciidoc'
pkgs+=' docbook2x'
pkgs+=' gcc'
pkgs+=' gettext'
pkgs+=' git '
pkgs+=' libcurl4-openssl-dev'
pkgs+=' libexpat1-dev'
pkgs+=' libssl-dev'
pkgs+=' make'
pkgs+=' openssl'
pkgs+=' tree'

sudo apt-get -y install $pkgs
git config --global user.name "Jeffrey S. Haemer"
git config --global user.email "jeffrey.haemer@gmail.com"

#[ -f $HOME/.ssh/id_rsa.pub ] || ssh-keygen
# now copy the public key to GitHub

# repos I'll want
mkdir -p ~/src; cd $_
for i in jsh/{dotfiles,git-scratch} git/git; do
  [ -d $(basename $i) ] || git clone git@github.com:$i
done

# install personal git tools
mkdir -p ~/bin
ln -f git-scratch/git-{addfile,scratch} $_

# use personal config
for i in dotfiles/.{b,gitc,v}*; do
  ln -f $i $HOME
done

# build and install newest official git release
git -C git checkout $(git -C git tag -l | grep -v rc | tail -1)
make -C git prefix=/usr all doc info
sudo make -C git prefix=/usr install install-doc install-html install-info
